songlist = [
    {'id': 'sayonarahatsukoi', 'title': 'Sayonara Hatsukoi', 'title_ja': '', 'set': 'base', 'levels': [1, 4, 6],
     'unlock': False},
    {'id': 'lostcivilization', 'title': 'Lost Civilization', 'title_ja': '', 'set': 'base', 'levels': [4, 7, 9],
     'unlock': False},
    {'id': 'goodtek', 'title': 'GOODTEK (Arcaea Edit)', 'title_ja': '', 'set': 'base', 'levels': [4, 6, 9],
     'unlock': True},
    {'id': 'viyella', 'title': 'cry of viyella', 'title_ja': '', 'set': 'core', 'levels': [3, 6, 8],
     'unlock': False},
    {'id': 'rise', 'title': 'Rise', 'title_ja': '', 'set': 'base', 'levels': [2, 4, 7], 'unlock': False},
    {'id': 'lucifer', 'title': 'Lucifer', 'title_ja': '', 'set': 'base', 'levels': [3, 5, 8], 'unlock': True},
    {'id': 'fairytale', 'title': 'Fairytale', 'title_ja': '', 'set': 'base', 'levels': [1, 3, 7],
     'unlock': False},
    {'id': 'hearditsaid', 'title': "I've heard it said", 'title_ja': '', 'set': 'core', 'levels': [3, 6, 8],
     'unlock': False},
    {'id': 'babaroque', 'title': 'Babaroque', 'title_ja': '', 'set': 'base', 'levels': [3, 6, 8],
     'unlock': True},
    {'id': 'memoryfactory', 'title': 'memoryfactory.lzh', 'title_ja': '', 'set': 'core', 'levels': [2, 5, 8],
     'unlock': False},
    {'id': 'snowwhite', 'title': 'Snow White', 'title_ja': '', 'set': 'base', 'levels': [2, 5, 8],
     'unlock': False},
    {'id': 'relentless', 'title': 'Relentless', 'title_ja': '', 'set': 'core', 'levels': [4, 6, 8],
     'unlock': False},
    {'id': 'shadesoflight', 'title': 'Shades of Light in a Transcendent Realm', 'title_ja': '', 'set': 'base',
     'levels': [3, 6, 8], 'unlock': True},
    {'id': 'vexaria', 'title': 'Vexaria', 'title_ja': '', 'set': 'base', 'levels': [2, 5, 7], 'unlock': False},
    {'id': 'essenceoftwilight', 'title': 'Essence of Twilight', 'title_ja': '', 'set': 'core',
     'levels': [4, 7, 9], 'unlock': True},
    {'id': 'qualia', 'title': 'qualia -ideaesthesia-', 'title_ja': '', 'set': 'base', 'levels': [5, 7, 9],
     'unlock': True},
    {'id': 'pragmatism', 'title': 'PRAGMATISM', 'title_ja': '', 'set': 'core', 'levels': [4, 8, 10],
     'unlock': True},
    {'id': 'sheriruth', 'title': 'Sheriruth', 'title_ja': '', 'set': 'core', 'levels': [5, 7, 10],
     'unlock': True},
    {'id': 'lumia', 'title': 'Lumia', 'title_ja': '', 'set': 'core', 'levels': [2, 6, 8], 'unlock': False},
    {'id': 'dement', 'title': 'Dement ~after legend~', 'title_ja': '', 'set': 'base', 'levels': [3, 6, 7],
     'unlock': False},
    {'id': 'dandelion', 'title': 'Dandelion', 'title_ja': '', 'set': 'base', 'levels': [2, 6, 8],
     'unlock': False},
    {'id': 'anokumene', 'title': 'Anökumene', 'title_ja': '', 'set': 'base', 'levels': [2, 6, 9],
     'unlock': True},
    {'id': 'infinityheaven', 'title': 'Infinity Heaven', 'title_ja': '', 'set': 'base', 'levels': [1, 5, 7],
     'unlock': False},
    {'id': 'partyvinyl', 'title': 'Party Vinyl', 'title_ja': '', 'set': 'shiawase', 'levels': [4, 7, 9],
     'unlock': False},
    {'id': 'flashback', 'title': 'Flashback', 'title_ja': '', 'set': 'shiawase', 'levels': [2, 5, 8],
     'unlock': False},
    {'id': 'flyburg', 'title': 'Flyburg and Endroll', 'title_ja': 'フライブルクとエンドロウル', 'set': 'shiawase',
     'levels': [3, 6, 9], 'unlock': False},
    {'id': 'nirvluce', 'title': 'Nirv lucE', 'title_ja': '', 'set': 'shiawase', 'levels': [2, 7, 10],
     'unlock': False},
    {'id': 'paradise', 'title': 'Paradise', 'title_ja': '', 'set': 'shiawase', 'levels': [1, 4, 7],
     'unlock': False},
    {'id': 'brandnewworld', 'title': 'Brand new world', 'title_ja': '', 'set': 'base', 'levels': [2, 4, 7],
     'unlock': False},
    {'id': 'dataerror', 'title': 'DataErr0r', 'title_ja': '', 'set': 'single', 'levels': [3, 7, 9],
     'unlock': False},
    {'id': 'crosssoul', 'title': 'CROSS†SOUL', 'title_ja': '', 'set': 'single', 'levels': [4, 7, 9],
     'unlock': False},
    {'id': 'yourvoiceso', 'title': 'Your voice so... feat. Such', 'title_ja': '', 'set': 'single',
     'levels': [3, 6, 9], 'unlock': False},
    {'id': 'chronostasis', 'title': 'Chronostasis', 'title_ja': '', 'set': 'base', 'levels': [3, 7, 9],
     'unlock': False},
    {'id': 'kanagawa', 'title': 'Kanagawa Cyber Culvert', 'title_ja': '神奈川電脳暗渠', 'set': 'base',
     'levels': [1, 5, 9], 'unlock': True},
    {'id': 'moonlightofsandcastle', 'title': 'Moonlight of Sand Castle', 'title_ja': '', 'set': 'dynamix',
     'levels': [1, 5, 7], 'unlock': False},
    {'id': 'reconstruction', 'title': 'REconstruction', 'title_ja': '', 'set': 'dynamix', 'levels': [2, 6, 8],
     'unlock': False},
    {'id': 'evoltex', 'title': "Evoltex (poppi'n mix)", 'title_ja': '', 'set': 'dynamix', 'levels': [2, 7, 8],
     'unlock': False},
    {'id': 'oracle', 'title': 'Oracle', 'title_ja': '', 'set': 'dynamix', 'levels': [3, 5, 9], 'unlock': False},
    {'id': 'aterlbus', 'title': 'αterlβus', 'title_ja': '', 'set': 'dynamix', 'levels': [4, 7, 10],
     'unlock': False},
    {'id': 'clotho', 'title': 'Clotho and the stargazer', 'title_ja': 'クロートーと星の観測者', 'set': 'base',
     'levels': [2, 5, 7], 'unlock': False},
    {'id': 'impurebird', 'title': 'Impure Bird', 'title_ja': '不浄な白い鳥', 'set': 'single', 'levels': [2, 5, 9],
     'unlock': False},
    {'id': 'ignotus', 'title': 'Ignotus', 'title_ja': '', 'set': 'base', 'levels': [3, 6, 9], 'unlock': True},
    {'id': 'lethaeus', 'title': 'Lethaeus', 'title_ja': '', 'set': 'mirai', 'levels': [3, 6, 9],
     'unlock': False},
    {'id': 'romancewars', 'title': 'Romance Wars', 'title_ja': 'vsキミ戦争', 'set': 'mirai', 'levels': [1, 4, 7],
     'unlock': False},
    {'id': 'blossoms', 'title': 'Blossoms', 'title_ja': '', 'set': 'mirai', 'levels': [1, 4, 7],
     'unlock': False},
    {'id': 'moonheart', 'title': 'Moonheart', 'title_ja': '', 'set': 'mirai', 'levels': [2, 5, 8],
     'unlock': False},
    {'id': 'genesis', 'title': 'Genesis', 'title_ja': '', 'set': 'mirai', 'levels': [2, 5, 8], 'unlock': False},
    {'id': 'harutopia', 'title': 'Harutopia ~Utopia of Spring~', 'title_ja': 'ハルトピア ~Utopia of Spring~',
     'set': 'base', 'levels': [1, 4, 8], 'unlock': True},
    {'id': 'auxesia', 'title': 'Auxesia', 'title_ja': '', 'set': 'single', 'levels': [3, 6, 9],
     'unlock': False},
    {'id': 'rabbitintheblackroom', 'title': 'Rabbit In The Black Room', 'title_ja': '', 'set': 'base',
     'levels': [2, 5, 8], 'unlock': True},
    {'id': 'modelista', 'title': 'Modelista', 'title_ja': '', 'set': 'single', 'levels': [3, 7, 9],
     'unlock': False},
    {'id': 'soundwitch', 'title': 'SOUNDWiTCH', 'title_ja': '', 'set': 'yugamu', 'levels': [3, 6, 9],
     'unlock': False},
    {'id': 'trappola', 'title': 'trappola bewitching', 'title_ja': '妖艶魔女 -trappola bewitching-',
     'set': 'yugamu', 'levels': [3, 6, 9], 'unlock': False},
    {'id': 'iconoclast', 'title': 'Iconoclast', 'title_ja': '', 'set': 'yugamu', 'levels': [4, 7, 9],
     'unlock': False},
    {'id': 'conflict', 'title': 'conflict', 'title_ja': '', 'set': 'yugamu', 'levels': [4, 7, 10],
     'unlock': False},
    {'id': 'axiumcrisis', 'title': 'Axium Crisis', 'title_ja': '', 'set': 'yugamu', 'levels': [5, 8, 10],
     'unlock': True},
    {'id': 'grievouslady', 'title': 'Grievous Lady', 'title_ja': '', 'set': 'yugamu', 'levels': [6, 9, 11],
     'unlock': False},
    {'id': 'dreaminattraction', 'title': "Dreamin' Attraction!!", 'title_ja': '', 'set': 'base',
     'levels': [4, 7, 9], 'unlock': True},
    {'id': 'redandblue', 'title': 'Red and Blue', 'title_ja': '', 'set': 'base', 'levels': [4, 7, 9],
     'unlock': True},
    {'id': 'onelastdrive', 'title': 'One Last Drive', 'title_ja': '', 'set': 'base', 'levels': [2, 5, 8],
     'unlock': False},
    {'id': 'surrender', 'title': 'Surrender', 'title_ja': '', 'set': 'single', 'levels': [3, 6, 8],
     'unlock': False}, {'id': 'yozakurafubuki', 'title': 'Yosakura Fubuki', 'title_ja': '夜桜吹雪', 'set': 'single',
                        'levels': [4, 7, 9], 'unlock': False},
    {'id': 'cyanine', 'title': 'cyanine', 'title_ja': '', 'set': 'lanota', 'levels': [4, 7, 10],
     'unlock': False},
    {'id': 'dreamgoeson', 'title': 'Dream goes on', 'title_ja': '', 'set': 'lanota', 'levels': [1, 5, 7],
     'unlock': False},
    {'id': 'journey', 'title': 'Journey', 'title_ja': '', 'set': 'lanota', 'levels': [3, 6, 8],
     'unlock': False},
    {'id': 'specta', 'title': 'Specta', 'title_ja': '', 'set': 'lanota', 'levels': [3, 6, 9], 'unlock': False},
    {'id': 'quon', 'title': 'Quon', 'title_ja': '', 'set': 'lanota', 'levels': [4, 6, 9], 'unlock': False},
    {'id': 'syro', 'title': 'Syro', 'title_ja': '', 'set': 'base', 'levels': [3, 6, 9], 'unlock': True},
    {'id': 'reinvent', 'title': 'Reinvent', 'title_ja': '', 'set': 'base', 'levels': [2, 6, 8],
     'unlock': False},
    {'id': 'silentrush', 'title': 'Silent Rush', 'title_ja': '', 'set': 'nijuusei', 'levels': [2, 5, 8],
     'unlock': False},
    {'id': 'singularity', 'title': 'Singularity', 'title_ja': '', 'set': 'nijuusei', 'levels': [4, 7, 10],
     'unlock': False},
    {'id': 'memoryforest', 'title': 'Memory Forest', 'title_ja': '', 'set': 'nijuusei', 'levels': [3, 6, 9],
     'unlock': False},
    {'id': 'strongholds', 'title': 'Strongholds', 'title_ja': '', 'set': 'nijuusei', 'levels': [2, 5, 9],
     'unlock': False},
    {'id': 'nexttoyou', 'title': 'next to you', 'title_ja': '', 'set': 'nijuusei', 'levels': [4, 7, 8],
     'unlock': False}, {'id': 'metallicpunisher', 'title': 'Metallic Punisher', 'title_ja': '', 'set': 'single',
                        'levels': [3, 7, 10], 'unlock': False},
    {'id': 'blaster', 'title': 'Blaster', 'title_ja': '', 'set': 'base', 'levels': [4, 7, 9], 'unlock': True},
    {'id': 'guardina', 'title': 'γuarδina', 'title_ja': '', 'set': 'single', 'levels': [4, 7, 10],
     'unlock': True},
    {'id': 'carminescythe', 'title': 'carmine:scythe', 'title_ja': '', 'set': 'single', 'levels': [4, 7, 9],
     'unlock': False},
    {'id': 'bethere', 'title': 'Be There', 'title_ja': '', 'set': 'single', 'levels': [4, 7, 9],
     'unlock': False},
    {'id': 'cyberneciacatharsis', 'title': 'Cybernecia Catharsis', 'title_ja': '', 'set': 'base',
     'levels': [4, 7, 9], 'unlock': True},
    {'id': 'callmyname', 'title': 'Call My Name feat. Yukacco', 'title_ja': '', 'set': 'single',
     'levels': [3, 6, 8], 'unlock': False},
    {'id': 'inkarusi', 'title': 'inkar-usi', 'title_ja': '', 'set': 'base', 'levels': [2, 4, 7],
     'unlock': False},
    {'id': 'mazenine', 'title': 'Maze No.9', 'title_ja': '九番目の迷路', 'set': 'rei', 'levels': [3, 3, 8],
     'unlock': False},
    {'id': 'themessage', 'title': 'The Message', 'title_ja': '', 'set': 'rei', 'levels': [3, 6, 9],
     'unlock': False},
    {'id': 'sulfur', 'title': 'Sulfur', 'title_ja': '', 'set': 'rei', 'levels': [4, 6, 9], 'unlock': False},
    {'id': 'halcyon', 'title': 'Halcyon', 'title_ja': '', 'set': 'rei', 'levels': [5, 8, 10], 'unlock': False},
    {'id': 'etherstrike', 'title': 'Ether Strike', 'title_ja': '', 'set': 'rei', 'levels': [5, 8, 10],
     'unlock': True},
    {'id': 'fractureray', 'title': 'Fracture Ray', 'title_ja': '', 'set': 'rei', 'levels': [6, 9, 11],
     'unlock': False},
    {'id': 'suomi', 'title': 'Suomi', 'title_ja': '', 'set': 'base', 'levels': [2, 5, 7], 'unlock': True},
    {'id': 'bookmaker', 'title': 'Bookmaker (2D Version)', 'title_ja': '', 'set': 'base', 'levels': [4, 6, 8],
     'unlock': True},
    {'id': 'darakunosono', 'title': 'Illegal Paradise', 'title_ja': '堕楽の園', 'set': 'base', 'levels': [2, 7, 9],
     'unlock': True},
    {'id': 'dropdead', 'title': 'dropdead', 'title_ja': '', 'set': 'single', 'levels': [1, 9, 8],
     'unlock': False},
    {'id': 'fallensquare', 'title': 'Fallensquare', 'title_ja': '', 'set': 'single', 'levels': [3, 7, 9],
     'unlock': False},
    {'id': 'nhelv', 'title': 'Nhelv', 'title_ja': '', 'set': 'base', 'levels': [3, 6, 9], 'unlock': True},
    {'id': 'espebranch', 'title': 'LunarOrbit -believe in the Espebranch road-', 'title_ja': '白道、多希望羊と信じありく。',
     'set': 'base', 'levels': [3, 6, 9], 'unlock': True},
    {'id': 'purgatorium', 'title': 'Purgatorium', 'title_ja': '', 'set': 'base', 'levels': [2, 6, 8],
     'unlock': False},
    {'id': 'hikari', 'title': 'Hikari', 'title_ja': '光', 'set': 'tonesphere', 'levels': [2, 6, 8],
     'unlock': False},
    {'id': 'stager', 'title': 'STAGER (ALL STAGE CLEAR)', 'title_ja': '', 'set': 'tonesphere',
     'levels': [3, 6, 9], 'unlock': False},
    {'id': 'hallofmirrors', 'title': 'Hall of Mirrors', 'title_ja': '', 'set': 'tonesphere',
     'levels': [3, 5, 8], 'unlock': False},
    {'id': 'linearaccelerator', 'title': 'Linear Accelerator', 'title_ja': '', 'set': 'tonesphere',
     'levels': [2, 6, 9], 'unlock': False},
    {'id': 'tiferet', 'title': 'Tiferet', 'title_ja': '', 'set': 'tonesphere', 'levels': [4, 7, 10],
     'unlock': False},
    {'id': 'alexandrite', 'title': 'Alexandrite', 'title_ja': '', 'set': 'single', 'levels': [4, 7, 9],
     'unlock': False},
    {'id': 'rugie', 'title': 'Rugie', 'title_ja': '', 'set': 'base', 'levels': [3, 6, 9], 'unlock': True},
    {'id': 'astraltale', 'title': 'Astral tale', 'title_ja': '', 'set': 'single', 'levels': [4, 7, 9],
     'unlock': True},
    {'id': 'phantasia', 'title': 'Phantasia', 'title_ja': '', 'set': 'single', 'levels': [4, 5, 9],
     'unlock': True},
    {'id': 'empireofwinter', 'title': 'Empire of Winter', 'title_ja': '', 'set': 'single', 'levels': [3, 6, 9],
     'unlock': True},
    {'id': 'merlin', 'title': 'MERLIN', 'title_ja': '', 'set': 'groovecoaster', 'levels': [3, 5, 8],
     'unlock': True},
    {'id': 'dxfullmetal', 'title': 'DX Choseinou Full Metal Shojo', 'title_ja': 'DX超性能フルメタル少女',
     'set': 'groovecoaster', 'levels': [3, 6, 9], 'unlock': True},
    {'id': 'omakeno', 'title': 'OMAKENO Stroke', 'title_ja': '', 'set': 'groovecoaster', 'levels': [3, 6, 9],
     'unlock': True}, {'id': 'scarletlance', 'title': 'Scarlet Lance', 'title_ja': '', 'set': 'groovecoaster',
                       'levels': [4, 7, 10], 'unlock': True},
    {'id': 'ouroboros', 'title': 'ouroboros -twin stroke of the end-', 'title_ja': '', 'set': 'groovecoaster',
     'levels': [4, 7, 10], 'unlock': True},
    {'id': 'libertas', 'title': 'Libertas', 'title_ja': '', 'set': 'single', 'levels': [3, 5, 9],
     'unlock': True},
    {'id': 'solitarydream', 'title': 'Solitary Dream', 'title_ja': '虚空の夢', 'set': 'core', 'levels': [4, 7, 8],
     'unlock': True},
    {'id': 'antithese', 'title': 'Antithese', 'title_ja': '', 'set': 'zettai', 'levels': [2, 5, 8],
     'unlock': True},
    {'id': 'corruption', 'title': 'Corruption', 'title_ja': '', 'set': 'zettai', 'levels': [3, 6, 9],
     'unlock': True},
    {'id': 'blackterritory', 'title': 'Black Territory', 'title_ja': '', 'set': 'zettai', 'levels': [3, 7, 9],
     'unlock': True},
    {'id': 'viciousheroism', 'title': 'Vicious Heroism', 'title_ja': '', 'set': 'zettai', 'levels': [4, 7, 9],
     'unlock': True},
    {'id': 'cyaegha', 'title': 'Cyaegha', 'title_ja': '', 'set': 'zettai', 'levels': [5, 8, 10],
     'unlock': True},
    {'id': 'revixy', 'title': 'ReviXy', 'title_ja': '', 'set': 'base', 'levels': [3, 6, 8], 'unlock': True},
    {'id': 'grimheart', 'title': 'Grimheart', 'title_ja': '', 'set': 'base', 'levels': [2, 5, 8],
     'unlock': True},
    {'id': 'vector', 'title': 'VECTOЯ', 'title_ja': '', 'set': 'base', 'levels': [3, 7, 9], 'unlock': True},
    {'id': 'supernova', 'title': 'SUPERNOVA', 'title_ja': '', 'set': 'base', 'levels': [3, 6, 9],
     'unlock': True},
    {'id': 'dottodot', 'title': 'Dot to Dot feat. shully', 'title_ja': '', 'set': 'single', 'levels': [3, 6, 8],
     'unlock': True},
    {'id': 'garakuta', 'title': 'Garakuta Doll Play', 'title_ja': '', 'set': 'chunithm', 'levels': [4, 6, 10],
     'unlock': True},
    {'id': 'ikazuchi', 'title': 'Ikazuchi', 'title_ja': '怒槌', 'set': 'chunithm', 'levels': [3, 7, 10],
     'unlock': True}, {'id': 'worldvanquisher', 'title': 'World Vanquisher', 'title_ja': '', 'set': 'chunithm',
                       'levels': [2, 5, 10], 'unlock': True},
    {'id': 'dreadnought', 'title': 'Dreadnought', 'title_ja': '', 'set': 'single', 'levels': [4, 7, 9],
     'unlock': True},
    {'id': 'particlearts', 'title': 'Particle Arts', 'title_ja': '', 'set': 'prelude', 'levels': [3, 6, 8],
     'unlock': True},
    {'id': 'vindication', 'title': 'Vindication', 'title_ja': '', 'set': 'prelude', 'levels': [4, 6, 9],
     'unlock': True},
    {'id': 'heavensdoor', 'title': 'Heavensdoor', 'title_ja': '', 'set': 'prelude', 'levels': [4, 7, 9],
     'unlock': True},
    {'id': 'ringedgenesis', 'title': 'Ringed Genesis', 'title_ja': '', 'set': 'prelude', 'levels': [5, 8, 10],
     'unlock': True},
    {'id': 'chelsea', 'title': 'Chelsea', 'title_ja': '', 'set': 'omatsuri', 'levels': [3, 6, 8],
     'unlock': True},
    {'id': 'aiueoon', 'title': 'AI[UE]OON', 'title_ja': '', 'set': 'omatsuri', 'levels': [3, 6, 9],
     'unlock': True},
    {'id': 'melodyoflove', 'title': 'A Wandering Melody of Love', 'title_ja': '迷える音色は恋の唄', 'set': 'omatsuri',
     'levels': [3, 7, 9], 'unlock': True},
    {'id': 'tiemedowngently', 'title': 'Tie me down gently', 'title_ja': '', 'set': 'omatsuri',
     'levels': [3, 5, 8], 'unlock': True},
    {'id': 'valhallazero', 'title': 'Valhalla:0', 'title_ja': '', 'set': 'omatsuri', 'levels': [4, 7, 10],
     'unlock': True},
    {'id': 'mirzam', 'title': 'Mirzam', 'title_ja': '', 'set': 'single', 'levels': [4, 7, 9], 'unlock': True},
    {'id': 'diode', 'title': 'Diode', 'title_ja': '', 'set': 'base', 'levels': [2, 5, 8], 'unlock': True},
    {'id': 'freefall', 'title': 'FREEF4LL', 'title_ja': '', 'set': 'base', 'levels': [4, 7, 8], 'unlock': True},
    {'id': 'gloryroad', 'title': 'GLORY：ROAD', 'title_ja': '', 'set': 'shiawase', 'levels': [4, 7, 10],
     'unlock': True},
    {'id': 'monochromeprincess', 'title': 'Monochrome Princess', 'title_ja': '', 'set': 'base',
     'levels': [4, 7, 9], 'unlock': True},
    {'id': 'heavenlycaress', 'title': 'Heavenly caress', 'title_ja': '', 'set': 'single', 'levels': [3, 7, 9],
     'unlock': True},
    {'id': 'senkyou', 'title': 'Senkyou', 'title_ja': '', 'set': 'base', 'levels': [3, 5, 8], 'unlock': True},
    {'id': 'filament', 'title': 'Filament', 'title_ja': '', 'set': 'single', 'levels': [4, 7, 9],
     'unlock': True},
    {'id': 'avantraze', 'title': 'Avant Raze', 'title_ja': '', 'set': 'single', 'levels': [3, 6, 9],
     'unlock': True},
    {'id': 'battlenoone', 'title': 'BATTLE NO.1', 'title_ja': '', 'set': 'single', 'levels': [3, 6, 9],
     'unlock': True}, {'id': 'laqryma', 'title': "La'qryma of the Wasteland", 'title_ja': '', 'set': 'single',
                       'levels': [3, 6, 9], 'unlock': True},
    {'id': 'einherjar', 'title': 'Einherjar Joker', 'title_ja': '', 'set': 'single', 'levels': [4, 7, 9],
     'unlock': True},
    {'id': 'izana', 'title': 'IZANA', 'title_ja': '', 'set': 'single', 'levels': [5, 8, 10], 'unlock': True},
    {'id': 'saikyostronger', 'title': 'SAIKYO STRONGER', 'title_ja': '最強STRONGER', 'set': 'single',
     'levels': [5, 9, 11], 'unlock': True},
    {'id': 'worldexecuteme', 'title': 'world.execute(me);', 'title_ja': '', 'set': 'base', 'levels': [3, 5, 8],
     'unlock': True},
    {'id': 'blrink', 'title': 'BLRINK', 'title_ja': '', 'set': 'prelude', 'levels': [3, 7, 9], 'unlock': True}]
songlist_by_set = {
    'base': [
        {'id': 'sayonarahatsukoi', 'title': 'Sayonara Hatsukoi', 'title_ja': '', 'set': 'base', 'levels': [1, 4, 6]},
        {'id': 'lostcivilization', 'title': 'Lost Civilization', 'title_ja': '', 'set': 'base', 'levels': [4, 7, 9]},
        {'id': 'goodtek', 'title': 'GOODTEK (Arcaea Edit)', 'title_ja': '', 'set': 'base', 'levels': [4, 6, 9]},
        {'id': 'rise', 'title': 'Rise', 'title_ja': '', 'set': 'base', 'levels': [2, 4, 7]},
        {'id': 'lucifer', 'title': 'Lucifer', 'title_ja': '', 'set': 'base', 'levels': [3, 5, 8]},
        {'id': 'fairytale', 'title': 'Fairytale', 'title_ja': '', 'set': 'base', 'levels': [1, 3, 7]},
        {'id': 'babaroque', 'title': 'Babaroque', 'title_ja': '', 'set': 'base', 'levels': [3, 6, 8]},
        {'id': 'snowwhite', 'title': 'Snow White', 'title_ja': '', 'set': 'base', 'levels': [2, 5, 8]},
        {'id': 'shadesoflight', 'title': 'Shades of Light in a Transcendent Realm', 'title_ja': '', 'set': 'base',
         'levels': [3, 6, 8]},
        {'id': 'vexaria', 'title': 'Vexaria', 'title_ja': '', 'set': 'base', 'levels': [2, 5, 7]},
        {'id': 'qualia', 'title': 'qualia -ideaesthesia-', 'title_ja': '', 'set': 'base', 'levels': [5, 7, 9]},
        {'id': 'dement', 'title': 'Dement ~after legend~', 'title_ja': '', 'set': 'base', 'levels': [3, 6, 7]},
        {'id': 'dandelion', 'title': 'Dandelion', 'title_ja': '', 'set': 'base', 'levels': [2, 6, 8]},
        {'id': 'anokumene', 'title': 'Anökumene', 'title_ja': '', 'set': 'base', 'levels': [2, 6, 9]},
        {'id': 'infinityheaven', 'title': 'Infinity Heaven', 'title_ja': '', 'set': 'base', 'levels': [1, 5, 7]},
        {'id': 'brandnewworld', 'title': 'Brand new world', 'title_ja': '', 'set': 'base', 'levels': [2, 4, 7]},
        {'id': 'chronostasis', 'title': 'Chronostasis', 'title_ja': '', 'set': 'base', 'levels': [3, 7, 9]},
        {'id': 'kanagawa', 'title': 'Kanagawa Cyber Culvert', 'title_ja': '神奈川電脳暗渠', 'set': 'base',
         'levels': [1, 5, 9]},
        {'id': 'clotho', 'title': 'Clotho and the stargazer', 'title_ja': 'クロートーと星の観測者', 'set': 'base',
         'levels': [2, 5, 7]},
        {'id': 'ignotus', 'title': 'Ignotus', 'title_ja': '', 'set': 'base', 'levels': [3, 6, 9]},
        {'id': 'harutopia', 'title': 'Harutopia ~Utopia of Spring~', 'title_ja': 'ハルトピア ~Utopia of Spring~',
         'set': 'base',
         'levels': [1, 4, 8]},
        {'id': 'rabbitintheblackroom', 'title': 'Rabbit In The Black Room', 'title_ja': '', 'set': 'base',
         'levels': [2, 5, 8]},
        {'id': 'dreaminattraction', 'title': "Dreamin' Attraction!!", 'title_ja': '', 'set': 'base',
         'levels': [4, 7, 9]},
        {'id': 'redandblue', 'title': 'Red and Blue', 'title_ja': '', 'set': 'base', 'levels': [4, 7, 9]},
        {'id': 'onelastdrive', 'title': 'One Last Drive', 'title_ja': '', 'set': 'base', 'levels': [2, 5, 8]},
        {'id': 'syro', 'title': 'Syro', 'title_ja': '', 'set': 'base', 'levels': [3, 6, 9]},
        {'id': 'reinvent', 'title': 'Reinvent', 'title_ja': '', 'set': 'base', 'levels': [2, 6, 8]},
        {'id': 'blaster', 'title': 'Blaster', 'title_ja': '', 'set': 'base', 'levels': [4, 7, 9]},
        {'id': 'cyberneciacatharsis', 'title': 'Cybernecia Catharsis', 'title_ja': '', 'set': 'base',
         'levels': [4, 7, 9]},
        {'id': 'inkarusi', 'title': 'inkar-usi', 'title_ja': '', 'set': 'base', 'levels': [2, 4, 7]},
        {'id': 'suomi', 'title': 'Suomi', 'title_ja': '', 'set': 'base', 'levels': [2, 5, 7]},
        {'id': 'bookmaker', 'title': 'Bookmaker (2D Version)', 'title_ja': '', 'set': 'base', 'levels': [4, 6, 8]},
        {'id': 'darakunosono', 'title': 'Illegal Paradise', 'title_ja': '堕楽の園', 'set': 'base', 'levels': [2, 7, 9]},
        {'id': 'nhelv', 'title': 'Nhelv', 'title_ja': '', 'set': 'base', 'levels': [3, 6, 9]},
        {'id': 'espebranch', 'title': 'LunarOrbit -believe in the Espebranch road-', 'title_ja': '白道、多希望羊と信じありく。',
         'set': 'base', 'levels': [3, 6, 9]},
        {'id': 'purgatorium', 'title': 'Purgatorium', 'title_ja': '', 'set': 'base', 'levels': [2, 6, 8]},
        {'id': 'rugie', 'title': 'Rugie', 'title_ja': '', 'set': 'base', 'levels': [3, 6, 9]},
        {'id': 'revixy', 'title': 'ReviXy', 'title_ja': '', 'set': 'base', 'levels': [3, 6, 8]},
        {'id': 'grimheart', 'title': 'Grimheart', 'title_ja': '', 'set': 'base', 'levels': [2, 5, 8]},
        {'id': 'vector', 'title': 'VECTOЯ', 'title_ja': '', 'set': 'base', 'levels': [3, 7, 9]},
        {'id': 'supernova', 'title': 'SUPERNOVA', 'title_ja': '', 'set': 'base', 'levels': [3, 6, 9]},
        {'id': 'diode', 'title': 'Diode', 'title_ja': '', 'set': 'base', 'levels': [2, 5, 8]},
        {'id': 'freefall', 'title': 'FREEF4LL', 'title_ja': '', 'set': 'base', 'levels': [4, 7, 8]},
        {'id': 'monochromeprincess', 'title': 'Monochrome Princess', 'title_ja': '', 'set': 'base',
         'levels': [4, 7, 9]},
        {'id': 'senkyou', 'title': 'Senkyou', 'title_ja': '', 'set': 'base', 'levels': [3, 5, 8]},
        {'id': 'worldexecuteme', 'title': 'world.execute(me);', 'title_ja': '', 'set': 'base', 'levels': [3, 5, 8]}
    ],
    'core': [
        {'id': 'viyella', 'title': 'cry of viyella', 'title_ja': '', 'set': 'core', 'levels': [3, 6, 8]},
        {'id': 'hearditsaid', 'title': "I've heard it said", 'title_ja': '', 'set': 'core',
         'levels': [3, 6, 8]},
        {'id': 'memoryfactory', 'title': 'memoryfactory.lzh', 'title_ja': '', 'set': 'core',
         'levels': [2, 5, 8]},
        {'id': 'relentless', 'title': 'Relentless', 'title_ja': '', 'set': 'core', 'levels': [4, 6, 8]},
        {'id': 'essenceoftwilight', 'title': 'Essence of Twilight', 'title_ja': '', 'set': 'core',
         'levels': [4, 7, 9]},
        {'id': 'pragmatism', 'title': 'PRAGMATISM', 'title_ja': '', 'set': 'core', 'levels': [4, 8, 10]},
        {'id': 'sheriruth', 'title': 'Sheriruth', 'title_ja': '', 'set': 'core', 'levels': [5, 7, 10]},
        {'id': 'lumia', 'title': 'Lumia', 'title_ja': '', 'set': 'core', 'levels': [2, 6, 8]},
        {'id': 'solitarydream', 'title': 'Solitary Dream', 'title_ja': '虚空の夢', 'set': 'core',
         'levels': [4, 7, 8]}
    ],
    'shiawase': [
        {'id': 'partyvinyl', 'title': 'Party Vinyl', 'title_ja': '', 'set': 'shiawase', 'levels': [4, 7, 9]},
        {'id': 'flashback', 'title': 'Flashback', 'title_ja': '', 'set': 'shiawase', 'levels': [2, 5, 8]},
        {'id': 'flyburg', 'title': 'Flyburg and Endroll', 'title_ja': 'フライブルクとエンドロウル', 'set': 'shiawase',
         'levels': [3, 6, 9]},
        {'id': 'nirvluce', 'title': 'Nirv lucE', 'title_ja': '', 'set': 'shiawase', 'levels': [2, 7, 10]},
        {'id': 'paradise', 'title': 'Paradise', 'title_ja': '', 'set': 'shiawase', 'levels': [1, 4, 7]},
        {'id': 'gloryroad', 'title': 'GLORY：ROAD', 'title_ja': '', 'set': 'shiawase', 'levels': [4, 7, 10]}
    ],
    'single': [
        {'id': 'dataerror', 'title': 'DataErr0r', 'title_ja': '', 'set': 'single', 'levels': [3, 7, 9]},
        {'id': 'crosssoul', 'title': 'CROSS†SOUL', 'title_ja': '', 'set': 'single', 'levels': [4, 7, 9]},
        {'id': 'yourvoiceso', 'title': 'Your voice so... feat. Such', 'title_ja': '', 'set': 'single',
         'levels': [3, 6, 9]},
        {'id': 'impurebird', 'title': 'Impure Bird', 'title_ja': '不浄な白い鳥', 'set': 'single',
         'levels': [2, 5, 9]},
        {'id': 'auxesia', 'title': 'Auxesia', 'title_ja': '', 'set': 'single', 'levels': [3, 6, 9]},
        {'id': 'modelista', 'title': 'Modelista', 'title_ja': '', 'set': 'single', 'levels': [3, 7, 9]},
        {'id': 'surrender', 'title': 'Surrender', 'title_ja': '', 'set': 'single', 'levels': [3, 6, 8]},
        {'id': 'yozakurafubuki', 'title': 'Yosakura Fubuki', 'title_ja': '夜桜吹雪', 'set': 'single',
         'levels': [4, 7, 9]},
        {'id': 'metallicpunisher', 'title': 'Metallic Punisher', 'title_ja': '', 'set': 'single',
         'levels': [3, 7, 10]},
        {'id': 'guardina', 'title': 'γuarδina', 'title_ja': '', 'set': 'single', 'levels': [4, 7, 10]},
        {'id': 'carminescythe', 'title': 'carmine:scythe', 'title_ja': '', 'set': 'single',
         'levels': [4, 7, 9]},
        {'id': 'bethere', 'title': 'Be There', 'title_ja': '', 'set': 'single', 'levels': [4, 7, 9]},
        {'id': 'callmyname', 'title': 'Call My Name feat. Yukacco', 'title_ja': '', 'set': 'single',
         'levels': [3, 6, 8]},
        {'id': 'dropdead', 'title': 'dropdead', 'title_ja': '', 'set': 'single', 'levels': [1, 9, 8]},
        {'id': 'fallensquare', 'title': 'Fallensquare', 'title_ja': '', 'set': 'single',
         'levels': [3, 7, 9]},
        {'id': 'alexandrite', 'title': 'Alexandrite', 'title_ja': '', 'set': 'single',
         'levels': [4, 7, 9]},
        {'id': 'astraltale', 'title': 'Astral tale', 'title_ja': '', 'set': 'single',
         'levels': [4, 7, 9]},
        {'id': 'phantasia', 'title': 'Phantasia', 'title_ja': '', 'set': 'single', 'levels': [4, 5, 9]},
        {'id': 'empireofwinter', 'title': 'Empire of Winter', 'title_ja': '', 'set': 'single',
         'levels': [3, 6, 9]},
        {'id': 'libertas', 'title': 'Libertas', 'title_ja': '', 'set': 'single', 'levels': [3, 5, 9]},
        {'id': 'dottodot', 'title': 'Dot to Dot feat. shully', 'title_ja': '', 'set': 'single',
         'levels': [3, 6, 8]},
        {'id': 'dreadnought', 'title': 'Dreadnought', 'title_ja': '', 'set': 'single',
         'levels': [4, 7, 9]},
        {'id': 'mirzam', 'title': 'Mirzam', 'title_ja': '', 'set': 'single', 'levels': [4, 7, 9]},
        {'id': 'heavenlycaress', 'title': 'Heavenly caress', 'title_ja': '', 'set': 'single',
         'levels': [3, 7, 9]},
        {'id': 'filament', 'title': 'Filament', 'title_ja': '', 'set': 'single', 'levels': [4, 7, 9]},
        {'id': 'avantraze', 'title': 'Avant Raze', 'title_ja': '', 'set': 'single', 'levels': [3, 6, 9]},
        {'id': 'battlenoone', 'title': 'BATTLE NO.1', 'title_ja': '', 'set': 'single',
         'levels': [3, 6, 9]},
        {'id': 'laqryma', 'title': "La'qryma of the Wasteland", 'title_ja': '', 'set': 'single',
         'levels': [3, 6, 9]},
        {'id': 'einherjar', 'title': 'Einherjar Joker', 'title_ja': '', 'set': 'single',
         'levels': [4, 7, 9]},
        {'id': 'izana', 'title': 'IZANA', 'title_ja': '', 'set': 'single', 'levels': [5, 8, 10]},
        {'id': 'saikyostronger', 'title': 'SAIKYO STRONGER', 'title_ja': '最強STRONGER', 'set': 'single',
         'levels': [5, 9, 11]}
    ],
    'dynamix': [
        {'id': 'moonlightofsandcastle', 'title': 'Moonlight of Sand Castle', 'title_ja': '', 'set': 'dynamix',
         'levels': [1, 5, 7]},
        {'id': 'reconstruction', 'title': 'REconstruction', 'title_ja': '', 'set': 'dynamix', 'levels': [2, 6, 8]},
        {'id': 'evoltex', 'title': "Evoltex (poppi'n mix)", 'title_ja': '', 'set': 'dynamix', 'levels': [2, 7, 8]},
        {'id': 'oracle', 'title': 'Oracle', 'title_ja': '', 'set': 'dynamix', 'levels': [3, 5, 9]},
        {'id': 'aterlbus', 'title': 'αterlβus', 'title_ja': '', 'set': 'dynamix', 'levels': [4, 7, 10]}
    ],
    'mirai': [
        {'id': 'lethaeus', 'title': 'Lethaeus', 'title_ja': '', 'set': 'mirai', 'levels': [3, 6, 9]},
        {'id': 'romancewars', 'title': 'Romance Wars', 'title_ja': 'vsキミ戦争', 'set': 'mirai', 'levels': [1, 4, 7]},
        {'id': 'blossoms', 'title': 'Blossoms', 'title_ja': '', 'set': 'mirai', 'levels': [1, 4, 7]},
        {'id': 'moonheart', 'title': 'Moonheart', 'title_ja': '', 'set': 'mirai', 'levels': [2, 5, 8]},
        {'id': 'genesis', 'title': 'Genesis', 'title_ja': '', 'set': 'mirai', 'levels': [2, 5, 8]}
    ],
    'yugamu': [
        {'id': 'soundwitch', 'title': 'SOUNDWiTCH', 'title_ja': '', 'set': 'yugamu', 'levels': [3, 6, 9]},
        {'id': 'trappola', 'title': 'trappola bewitching', 'title_ja': '妖艶魔女 -trappola bewitching-', 'set': 'yugamu',
         'levels': [3, 6, 9]},
        {'id': 'iconoclast', 'title': 'Iconoclast', 'title_ja': '', 'set': 'yugamu', 'levels': [4, 7, 9]},
        {'id': 'conflict', 'title': 'conflict', 'title_ja': '', 'set': 'yugamu', 'levels': [4, 7, 10]},
        {'id': 'axiumcrisis', 'title': 'Axium Crisis', 'title_ja': '', 'set': 'yugamu', 'levels': [5, 8, 10]},
        {'id': 'grievouslady', 'title': 'Grievous Lady', 'title_ja': '', 'set': 'yugamu', 'levels': [6, 9, 11]}
    ],
    'lanota': [
        {'id': 'cyanine', 'title': 'cyanine', 'title_ja': '', 'set': 'lanota', 'levels': [4, 7, 10]},
        {'id': 'dreamgoeson', 'title': 'Dream goes on', 'title_ja': '', 'set': 'lanota',
         'levels': [1, 5, 7]},
        {'id': 'journey', 'title': 'Journey', 'title_ja': '', 'set': 'lanota', 'levels': [3, 6, 8]},
        {'id': 'specta', 'title': 'Specta', 'title_ja': '', 'set': 'lanota', 'levels': [3, 6, 9]},
        {'id': 'quon', 'title': 'Quon', 'title_ja': '', 'set': 'lanota', 'levels': [4, 6, 9]}
    ],
    'nijuusei': [
        {'id': 'silentrush', 'title': 'Silent Rush', 'title_ja': '', 'set': 'nijuusei',
         'levels': [2, 5, 8]},
        {'id': 'singularity', 'title': 'Singularity', 'title_ja': '', 'set': 'nijuusei',
         'levels': [4, 7, 10]},
        {'id': 'memoryforest', 'title': 'Memory Forest', 'title_ja': '', 'set': 'nijuusei',
         'levels': [3, 6, 9]},
        {'id': 'strongholds', 'title': 'Strongholds', 'title_ja': '', 'set': 'nijuusei',
         'levels': [2, 5, 9]},
        {'id': 'nexttoyou', 'title': 'next to you', 'title_ja': '', 'set': 'nijuusei',
         'levels': [4, 7, 8]}
    ],
    'rei': [
        {'id': 'mazenine', 'title': 'Maze No.9', 'title_ja': '九番目の迷路', 'set': 'rei', 'levels': [3, 3, 8]},
        {'id': 'themessage', 'title': 'The Message', 'title_ja': '', 'set': 'rei', 'levels': [3, 6, 9]},
        {'id': 'sulfur', 'title': 'Sulfur', 'title_ja': '', 'set': 'rei', 'levels': [4, 6, 9]},
        {'id': 'halcyon', 'title': 'Halcyon', 'title_ja': '', 'set': 'rei', 'levels': [5, 8, 10]},
        {'id': 'etherstrike', 'title': 'Ether Strike', 'title_ja': '', 'set': 'rei', 'levels': [5, 8, 10]},
        {'id': 'fractureray', 'title': 'Fracture Ray', 'title_ja': '', 'set': 'rei', 'levels': [6, 9, 11]}
    ],
    'tonesphere': [
        {'id': 'hikari', 'title': 'Hikari', 'title_ja': '光', 'set': 'tonesphere', 'levels': [2, 6, 8]},
        {'id': 'stager', 'title': 'STAGER (ALL STAGE CLEAR)', 'title_ja': '', 'set': 'tonesphere',
         'levels': [3, 6, 9]},
        {'id': 'hallofmirrors', 'title': 'Hall of Mirrors', 'title_ja': '', 'set': 'tonesphere',
         'levels': [3, 5, 8]},
        {'id': 'linearaccelerator', 'title': 'Linear Accelerator', 'title_ja': '', 'set': 'tonesphere',
         'levels': [2, 6, 9]}, {'id': 'tiferet', 'title': 'Tiferet', 'title_ja': '', 'set': 'tonesphere',
                                'levels': [4, 7, 10]}
    ],
    'groovecoaster': [
        {'id': 'merlin', 'title': 'MERLIN', 'title_ja': '', 'set': 'groovecoaster', 'levels': [3, 5, 8]},
        {'id': 'dxfullmetal', 'title': 'DX Choseinou Full Metal Shojo', 'title_ja': 'DX超性能フルメタル少女',
         'set': 'groovecoaster', 'levels': [3, 6, 9]},
        {'id': 'omakeno', 'title': 'OMAKENO Stroke', 'title_ja': '', 'set': 'groovecoaster', 'levels': [3, 6, 9]},
        {'id': 'scarletlance', 'title': 'Scarlet Lance', 'title_ja': '', 'set': 'groovecoaster', 'levels': [4, 7, 10]},
        {'id': 'ouroboros', 'title': 'ouroboros -twin stroke of the end-', 'title_ja': '', 'set': 'groovecoaster',
         'levels': [4, 7, 10]}
    ],
    'zettai': [
        {'id': 'antithese', 'title': 'Antithese', 'title_ja': '', 'set': 'zettai', 'levels': [2, 5, 8]},
        {'id': 'corruption', 'title': 'Corruption', 'title_ja': '', 'set': 'zettai', 'levels': [3, 6, 9]},
        {'id': 'blackterritory', 'title': 'Black Territory', 'title_ja': '', 'set': 'zettai', 'levels': [3, 7, 9]},
        {'id': 'viciousheroism', 'title': 'Vicious Heroism', 'title_ja': '', 'set': 'zettai', 'levels': [4, 7, 9]},
        {'id': 'cyaegha', 'title': 'Cyaegha', 'title_ja': '', 'set': 'zettai', 'levels': [5, 8, 10]}
    ],
    'chunithm': [
        {'id': 'garakuta', 'title': 'Garakuta Doll Play', 'title_ja': '', 'set': 'chunithm', 'levels': [4, 6, 10]},
        {'id': 'ikazuchi', 'title': 'Ikazuchi', 'title_ja': '怒槌', 'set': 'chunithm', 'levels': [3, 7, 10]},
        {'id': 'worldvanquisher', 'title': 'World Vanquisher', 'title_ja': '', 'set': 'chunithm',
         'levels': [2, 5, 10]}
    ],
    'prelude': [
        {'id': 'particlearts', 'title': 'Particle Arts', 'title_ja': '', 'set': 'prelude', 'levels': [3, 6, 8]},
        {'id': 'vindication', 'title': 'Vindication', 'title_ja': '', 'set': 'prelude', 'levels': [4, 6, 9]},
        {'id': 'heavensdoor', 'title': 'Heavensdoor', 'title_ja': '', 'set': 'prelude', 'levels': [4, 7, 9]},
        {'id': 'ringedgenesis', 'title': 'Ringed Genesis', 'title_ja': '', 'set': 'prelude', 'levels': [5, 8, 10]},
        {'id': 'blrink', 'title': 'BLRINK', 'title_ja': '', 'set': 'prelude', 'levels': [3, 7, 9]}
    ],
    'omatsuri': [
        {'id': 'chelsea', 'title': 'Chelsea', 'title_ja': '', 'set': 'omatsuri', 'levels': [3, 6, 8]},
        {'id': 'aiueoon', 'title': 'AI[UE]OON', 'title_ja': '', 'set': 'omatsuri', 'levels': [3, 6, 9]},
        {'id': 'melodyoflove', 'title': 'A Wandering Melody of Love', 'title_ja': '迷える音色は恋の唄', 'set': 'omatsuri',
         'levels': [3, 7, 9]},
        {'id': 'tiemedowngently', 'title': 'Tie me down gently', 'title_ja': '', 'set': 'omatsuri',
         'levels': [3, 5, 8]},
        {'id': 'valhallazero', 'title': 'Valhalla:0', 'title_ja': '', 'set': 'omatsuri', 'levels': [4, 7, 10]}
    ]
}
songs_by_id = ['sayonarahatsukoi', 'lostcivilization', 'goodtek', 'viyella', 'rise', 'lucifer', 'fairytale',
               'hearditsaid', 'babaroque', 'memoryfactory', 'snowwhite', 'relentless', 'shadesoflight', 'vexaria',
               'essenceoftwilight', 'qualia', 'pragmatism', 'sheriruth', 'lumia', 'dement', 'dandelion', 'anokumene',
               'infinityheaven', 'partyvinyl', 'flashback', 'flyburg', 'nirvluce', 'paradise', 'brandnewworld',
               'dataerror', 'crosssoul', 'yourvoiceso', 'chronostasis', 'kanagawa', 'moonlightofsandcastle',
               'reconstruction', 'evoltex', 'oracle', 'aterlbus', 'clotho', 'impurebird', 'ignotus', 'lethaeus',
               'romancewars', 'blossoms', 'moonheart', 'genesis', 'harutopia', 'auxesia', 'rabbitintheblackroom',
               'modelista', 'soundwitch', 'trappola', 'iconoclast', 'conflict', 'axiumcrisis', 'grievouslady',
               'dreaminattraction', 'redandblue', 'onelastdrive', 'surrender', 'yozakurafubuki', 'cyanine',
               'dreamgoeson', 'journey', 'specta', 'quon', 'syro', 'reinvent', 'silentrush', 'singularity',
               'memoryforest', 'strongholds', 'nexttoyou', 'metallicpunisher', 'blaster', 'guardina', 'carminescythe',
               'bethere', 'cyberneciacatharsis', 'callmyname', 'inkarusi', 'mazenine', 'themessage', 'sulfur',
               'halcyon', 'etherstrike', 'fractureray', 'suomi', 'bookmaker', 'darakunosono', 'dropdead',
               'fallensquare', 'nhelv', 'espebranch', 'purgatorium', 'hikari', 'stager', 'hallofmirrors',
               'linearaccelerator', 'tiferet', 'alexandrite', 'rugie', 'astraltale', 'phantasia', 'empireofwinter',
               'merlin', 'dxfullmetal', 'omakeno', 'scarletlance', 'ouroboros', 'libertas', 'solitarydream',
               'antithese', 'corruption', 'blackterritory', 'viciousheroism', 'cyaegha', 'revixy', 'grimheart',
               'vector', 'supernova', 'dottodot', 'garakuta', 'ikazuchi', 'worldvanquisher', 'dreadnought',
               'particlearts', 'vindication', 'heavensdoor', 'ringedgenesis', 'chelsea', 'aiueoon', 'melodyoflove',
               'tiemedowngently', 'valhallazero', 'mirzam', 'diode', 'freefall', 'gloryroad', 'monochromeprincess',
               'heavenlycaress', 'senkyou', 'filament', 'avantraze', 'battlenoone', 'laqryma', 'einherjar', 'izana',
               'saikyostronger', 'worldexecuteme', 'blrink']
